spring:
  application:
    name: railway-main-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:${HOME}/Sites/railways/railway-backend/railway-secrets/main-secrets/main-${spring.profiles.active}.properties

server:
  port: 8081
